### ISSUE TITLE
alkudata_pupesoft7.sql

### ISSUE THREAD

**Issue by jarnurm** [akirjavainen/pupesoft7#1]
Alkudatan ajaminen ei onnistu. INSERT -lauseista tulee virheitä, koska kenttien määrä ei täsmää.

**Comment by akirjavainen** [comment]
Kiitos viestistä ja totta, tämä tiedosto ei ole ajan tasalla. Yritän päivitellä sen huomisen aikana.

**Comment by akirjavainen** [comment]
Alkudata on nyt päivitetty.

**Comment by jarnurm** [comment]
Kiitos! Nyt tulee enää yksi virhe:

ERROR 1062 (23000) at line 3119: Duplicate entry 'demo--Asentaja-tilauskasittely/tuote_selaus_haku.php-' for key 'oikeu.oikeudet_index'

Duplikaatteja on paljon. Tauluun oikeu on menossa 5877 riviä. Saisitko vielä tämän korjattua?

**Comment by akirjavainen** [comment]
Sieltä täytyi vähän rivejä karsia. Tämäkin nyt korjattu.
